name: yt_ecommerce_admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.20.2
  lottie: ^3.1.0
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.1.0
  url_launcher: ^6.2.6
  flutter_dropzone: ^4.2.1
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^6.0.3
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  # Web Specific
  web: ^1.1.0
  http: ^1.2.1
  html: ^0.15.4
  fl_chart: ^0.70.2
  data_table_2: ^2.5.12
  url_strategy: ^0.3.0
  universal_html: ^2.2.4

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 800