// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFY2vOeI4-OXSVYPOah8yZSXLRRnBP_9U',
    appId: '1:879663521770:web:1da7a4d07d6d0fcd685c93',
    messagingSenderId: '879663521770',
    projectId: 'e-commerce-user-f3290',
    authDomain: 'e-commerce-user-f3290.firebaseapp.com',
    storageBucket: 'e-commerce-user-f3290.firebasestorage.app',
    measurementId: 'G-VYBZBVZ86H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKjvfJd6atHWWWeX9gVnMSa_sz0btVu54',
    appId: '1:879663521770:android:2424f741b158b3de685c93',
    messagingSenderId: '879663521770',
    projectId: 'e-commerce-user-f3290',
    storageBucket: 'e-commerce-user-f3290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh0ndwC5NpShv0VLI8G-wONfXasxOFgUM',
    appId: '1:879663521770:ios:31edb75ca3daf88c685c93',
    messagingSenderId: '879663521770',
    projectId: 'e-commerce-user-f3290',
    storageBucket: 'e-commerce-user-f3290.firebasestorage.app',
    androidClientId: '879663521770-dc9ipn03b80o6v2tmaut7cg191qa4eb5.apps.googleusercontent.com',
    iosClientId: '879663521770-6ui48n6dcbhlj4f8grjouv096b8hbpdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );
}
